fix: fixed environment variables for crontab (#257)
* fix: fixed environment variables

* fix: fixed cronjob-daily script

* fix: fixed loging of errors

diff --git a/cronjobs/cronjob-daily b/cronjobs/cronjob-daily
--- a/cronjobs/cronjob-daily
+++ b/cronjobs/cronjob-daily
@@ -12,42 +12,76 @@
 # License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 # either express or implied.
 #
+
+check_success_message () {
+  # $1 - message to log in case if there's no success message
+  SUCCESS_MESSAGE=$(head -n1 "$SUCCESSFUL_MESSAGES_LOG")
+  if [[ -z "$SUCCESS_MESSAGE" ]]  # True if "$SUCCESS_MESSAGE" is empty
+  then
+    python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "$1" --filename "cronjob-daily"
+    exit 1
+  fi
+  truncate -s 0 "$SUCCESSFUL_MESSAGES_LOG"
+}
+
 START=$(date "+%s")
 python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "" --status "In Progress" --filename "cronjob-daily"
 #source activate
 source "$CONF"/configure.sh
+truncate -s 0 "$SUCCESSFUL_MESSAGES_LOG"
 date +"%c: Downloading from GitHub YangModels"
 {
-  DOWNLOAD_GITHUB_STATUS=$(./run_download_github.sh)
+  ./run_download_github.sh
+  check_success_message "GitHub download failed"
+  DOWNLOAD_GITHUB_STATUS="$SUCCESS_MESSAGE"
+  echo "$DOWNLOAD_GITHUB_STATUS"
 } || {
-  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "GitHub download failed" --filename "cronjob-daily" && exit 1
+  check_success_message "GitHub download failed"
 }
 date +"%c: Starting run_ietf_module_extraction.sh"
+
 {
-  IETF_MODULES_EXTRACTION_MESSAGE=$("$VIRTUAL_ENV"/ietf_modules_extraction/run_ietf_module_extraction.sh)
+  "$VIRTUAL_ENV"/ietf_modules_extraction/run_ietf_module_extraction.sh
+  check_success_message "IETF modules extraction failed, check the logs for more details: $LOGS/extract_ietf_modules.log"
+  IETF_MODULES_EXTRACTION_MESSAGE="$SUCCESS_MESSAGE"
+  echo "$IETF_MODULES_EXTRACTION_MESSAGE"
 } || {
-  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "IETF modules extraction failed, check the logs for more details: $LOGS/extract_ietf_modules.log" --filename "cronjob-daily" && exit 1
+  check_success_message "IETF modules extraction failed, check the logs for more details: $LOGS/extract_ietf_modules.log"
 }
+
 date +"%c: Starting run_module_compilation.sh"
 {
-  MODULES_COMPILATION_MESSAGE=$("$VIRTUAL_ENV"/modules_compilation/run_module_compilation.sh)
+  "$VIRTUAL_ENV"/modules_compilation/run_module_compilation.sh
+  check_success_message "Modules compilation failed, check the logs for more details: $LOGS/compile_modules.log"
+  MODULES_COMPILATION_MESSAGE="$SUCCESS_MESSAGE"
+  echo "$MODULES_COMPILATION_MESSAGE"
 } || {
-  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "Modules compilation failed, check the logs for more details: $LOGS/compile_modules.log" --filename "cronjob-daily" && exit 1
+  check_success_message "Modules compilation failed, check the logs for more details: $LOGS/compile_modules.log"
 }
 date +"%c: Starting rename_file_backup.py"
 mkdir -p "$BACKUPDIR"
-python "$VIRTUAL_ENV"/rename_file_backup.py
+{
+  python "$VIRTUAL_ENV"/rename_file_backup.py
+} || {
+  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "rename_file_backup.py script failed" --filename "cronjob-daily" && exit 1
+}
 date +"%c: Starting run_generate_main_page.sh"
 {
-  MAIN_PAGE_GENERATION_MESSAGE=$("$VIRTUAL_ENV"/main_page_generation/run_generate_main_page.sh)
+  "$VIRTUAL_ENV"/main_page_generation/run_generate_main_page.sh
+  check_success_message "Main page generation failed"
+  MAIN_PAGE_GENERATION_MESSAGE="$SUCCESS_MESSAGE"
+  echo "$MAIN_PAGE_GENERATION_MESSAGE"
 } || {
-  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "Main page generation failed" --filename "cronjob-daily" && exit 1
+  check_success_message "Main page generation failed"
 }
 date +"%c: Starting run_generate_figures_and_stats.sh"
 {
-  FIGURES_AND_STATS_GENERATION_MESSAGE=$("$VIRTUAL_ENV"/figures_and_stats/run_generate_figures_and_stats.sh)
+  "$VIRTUAL_ENV"/figures_and_stats/run_generate_figures_and_stats.sh
+  check_success_message "Figures and stats generation failed, check the logs for more details: $LOGS/generate_figures_and_stats.log"
+  FIGURES_AND_STATS_GENERATION_MESSAGE="$SUCCESS_MESSAGE"
+  echo "$FIGURES_AND_STATS_GENERATION_MESSAGE"
 } || {
-  python "$VIRTUAL_ENV"/job_log.py --start "$START" --end "$(date "+%s")" --status "Fail" --error "Figures and stats generation failed, check the logs for more details: $LOGS/generate_figures_and_stats.log" --filename "cronjob-daily" && exit 1
+  check_success_message "Figures and stats generation failed, check the logs for more details: $LOGS/generate_figures_and_stats.log"
 }
 
 # This are simple files for other Yang Catalog to know which files have been created
